// Code generated by Kitex v0.0.8. DO NOT EDIT.

package taskservice

import (
	"alert/kitex_gen/api"
	"alert/kitex_gen/rpc_dto"
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return taskServiceServiceInfo
}

var taskServiceServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "TaskService"
	handlerType := (*api.TaskService)(nil)
	methods := map[string]kitex.MethodInfo{
		"SelectTask":         kitex.NewMethodInfo(selectTaskHandler, newTaskServiceSelectTaskArgs, newTaskServiceSelectTaskResult, false),
		"AddTask":            kitex.NewMethodInfo(addTaskHandler, newTaskServiceAddTaskArgs, newTaskServiceAddTaskResult, false),
		"UpdateTaskEnable":   kitex.NewMethodInfo(updateTaskEnableHandler, newTaskServiceUpdateTaskEnableArgs, newTaskServiceUpdateTaskEnableResult, false),
		"SelectRunnableTask": kitex.NewMethodInfo(selectRunnableTaskHandler, newTaskServiceSelectRunnableTaskArgs, newTaskServiceSelectRunnableTaskResult, false),
		"DeleteTask":         kitex.NewMethodInfo(deleteTaskHandler, newTaskServiceDeleteTaskArgs, newTaskServiceDeleteTaskResult, false),
		"UpdateTask":         kitex.NewMethodInfo(updateTaskHandler, newTaskServiceUpdateTaskArgs, newTaskServiceUpdateTaskResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.0.8",
		Extra:           extra,
	}
	return svcInfo
}

func selectTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TaskServiceSelectTaskArgs)
	realResult := result.(*api.TaskServiceSelectTaskResult)
	success, err := handler.(api.TaskService).SelectTask(ctx, realArg.Code)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTaskServiceSelectTaskArgs() interface{} {
	return api.NewTaskServiceSelectTaskArgs()
}

func newTaskServiceSelectTaskResult() interface{} {
	return api.NewTaskServiceSelectTaskResult()
}

func addTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TaskServiceAddTaskArgs)
	realResult := result.(*api.TaskServiceAddTaskResult)
	success, err := handler.(api.TaskService).AddTask(ctx, realArg.Name, realArg.Code, realArg.RuleId, realArg.Frequency)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTaskServiceAddTaskArgs() interface{} {
	return api.NewTaskServiceAddTaskArgs()
}

func newTaskServiceAddTaskResult() interface{} {
	return api.NewTaskServiceAddTaskResult()
}

func updateTaskEnableHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TaskServiceUpdateTaskEnableArgs)

	err := handler.(api.TaskService).UpdateTaskEnable(ctx, realArg.Code, realArg.Enable)
	if err != nil {
		return err
	}

	return nil
}
func newTaskServiceUpdateTaskEnableArgs() interface{} {
	return api.NewTaskServiceUpdateTaskEnableArgs()
}

func newTaskServiceUpdateTaskEnableResult() interface{} {
	return api.NewTaskServiceUpdateTaskEnableResult()
}

func selectRunnableTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*api.TaskServiceSelectRunnableTaskResult)
	success, err := handler.(api.TaskService).SelectRunnableTask(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTaskServiceSelectRunnableTaskArgs() interface{} {
	return api.NewTaskServiceSelectRunnableTaskArgs()
}

func newTaskServiceSelectRunnableTaskResult() interface{} {
	return api.NewTaskServiceSelectRunnableTaskResult()
}

func deleteTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TaskServiceDeleteTaskArgs)

	err := handler.(api.TaskService).DeleteTask(ctx, realArg.Code)
	if err != nil {
		return err
	}

	return nil
}
func newTaskServiceDeleteTaskArgs() interface{} {
	return api.NewTaskServiceDeleteTaskArgs()
}

func newTaskServiceDeleteTaskResult() interface{} {
	return api.NewTaskServiceDeleteTaskResult()
}

func updateTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TaskServiceUpdateTaskArgs)

	err := handler.(api.TaskService).UpdateTask(ctx, realArg.Task)
	if err != nil {
		return err
	}

	return nil
}
func newTaskServiceUpdateTaskArgs() interface{} {
	return api.NewTaskServiceUpdateTaskArgs()
}

func newTaskServiceUpdateTaskResult() interface{} {
	return api.NewTaskServiceUpdateTaskResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SelectTask(ctx context.Context, code string) (r *rpc_dto.TaskResponse, err error) {
	var _args api.TaskServiceSelectTaskArgs
	_args.Code = code
	var _result api.TaskServiceSelectTaskResult
	if err = p.c.Call(ctx, "SelectTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddTask(ctx context.Context, name string, code string, ruleId int64, frequency int64) (r *rpc_dto.TaskResponse, err error) {
	var _args api.TaskServiceAddTaskArgs
	_args.Name = name
	_args.Code = code
	_args.RuleId = ruleId
	_args.Frequency = frequency
	var _result api.TaskServiceAddTaskResult
	if err = p.c.Call(ctx, "AddTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateTaskEnable(ctx context.Context, code string, enable bool) (err error) {
	var _args api.TaskServiceUpdateTaskEnableArgs
	_args.Code = code
	_args.Enable = enable
	var _result api.TaskServiceUpdateTaskEnableResult
	if err = p.c.Call(ctx, "UpdateTaskEnable", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) SelectRunnableTask(ctx context.Context) (r *rpc_dto.TasksResponse, err error) {
	var _args api.TaskServiceSelectRunnableTaskArgs
	var _result api.TaskServiceSelectRunnableTaskResult
	if err = p.c.Call(ctx, "SelectRunnableTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteTask(ctx context.Context, code string) (err error) {
	var _args api.TaskServiceDeleteTaskArgs
	_args.Code = code
	var _result api.TaskServiceDeleteTaskResult
	if err = p.c.Call(ctx, "DeleteTask", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) UpdateTask(ctx context.Context, task *rpc_dto.Task) (err error) {
	var _args api.TaskServiceUpdateTaskArgs
	_args.Task = task
	var _result api.TaskServiceUpdateTaskResult
	if err = p.c.Call(ctx, "UpdateTask", &_args, &_result); err != nil {
		return
	}
	return nil
}
